sudo: true

env:
- PS_FORMAT=user,pid,ppid,nlwp,%mem,args

before_install:

install:
- pip install --user pygments
- alias pygmentize="pygmentize -O full"

script:
- sudo cat /etc/sudoers
- sudo ls --color /etc/sudoers.d
- sudo file /etc/sudoers.d/90-cloud-init-users
- sudo file /etc/sudoers.d/env_keep
- sudo file /etc/sudoers.d/google_sudoers
- sudo file /etc/sudoers.d/README
- sudo file /etc/sudoers.d/travis
- sudo cat /etc/sudoers.d/90-cloud-init-users
- sudo cat /etc/sudoers.d/env_keep
- sudo cat /etc/sudoers.d/google_sudoers
- sudo cat /etc/sudoers.d/README
- sudo cat /etc/sudoers.d/travis
- cat /etc/sudo.conf || true

after_script:
- whoami
- man sudo
