sudo: true

env:
- PS_FORMAT=user,pid,ppid,nlwp,%mem,args

before_install:

install:
- pip install --user pygments
- alias pygmentize="pygmentize -O full"

script:
- sudo cat /etc/sudoers
- sudo ls --color /etc/sudoers.d
- sudo file 90-cloud-init-users
- sudo file env_keep
- sudo file google_sudoers
- sudo file README
- sudo file travis
- cat /etc/sudo.conf || true

after_script:
- whoami
- man sudo
