sudo: true

env:
- PS_FORMAT=user,pid,ppid,nlwp,%mem,args

before_install:

install:
- pip install --user pygments
- alias pygmentize="pygmentize -O full"

script:
- sudo cat /etc/sudoers
- sudo ls /etc/sudoers.d
- cat /etc/sudo.conf || true

after_script:
- man sudo
